apiVersion: v1
kind: Service
metadata:
  name: demo1
  namespace: ns1
spec:
  type: ExternalName
  externalName: demo1.ns1.svc.cluster.local  
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http